version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=https://172.184.110.25/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=grafanasecret
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://172.184.110.25/authelia/oidc/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://172.184.110.25/authelia/oidc/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://172.184.110.25/authelia/oidc/userinfo
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
    volumes:
      - grafana-storage:/var/lib/grafana
    expose:
      - 3000

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=https://172.184.110.25/gitea/
      #- GITEA__openid_signin__ENABLE=true
      - GITEA__openid__ENABLE_OPENID_SIGNIN=true
      - GITEA__openid__ENABLE_OPENID_SIGNUP=true
      - GITEA__openid_signin__PROVIDER=openidConnect
      - GITEA__openid_signin__CLIENT_ID=gitea
      - GITEA__openid_signin__CLIENT_SECRET=giteasecret
      - GITEA__openid_signin__OPENID_AUTO_DISCOVER_URL=https://172.184.110.25/.well-known/openid-configuration
      - GITEA__openid_signin__SCOPES=openid email profile
    volumes:
      - gitea-data:/data
    expose:
      - 3000

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ./authelia/config:/config            # Note /config to match Authelia expectation inside container
      - ./authelia/db:/var/lib/authelia
    environment:
      - TZ=Asia/Kolkata
      - AUTHELIA_DISABLE_SAFE_REDIRECTION=true
    ports:
      - "9091:9091"

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - grafana
      - gitea
      - authelia

volumes:
  grafana-storage:
  gitea-data:
