server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: gitea-logs
    pipeline_stages:
    static_configs:
      - targets:
          - localhost
        labels:
          job: gitea
          __path__: /var/lib/docker/containers/*/*-json.log

  - job_name: authelia-logs
    pipeline_stages:
    static_configs:
      - targets:
          - localhost
        labels:
          job: authelia
          __path__: /var/lib/docker/containers/*/*-json.log
